version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    command: go run main.go
    depends_on:
      - db
    networks:
      - technodom
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=techno
      - POSTGRES_PASSWORD=techno
      - POSTGRES_DB=techno
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - technodom


volumes:
  postgres-db:


networks:
  technodom:
    driver: bridge

