version: "3.8"

services:
  merchant:
    container_name: merchant
    build: ./
    command: ./merchant
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      DD_DB_HOST: database


  database:
    container_name: postgres12
    restart: always
    image: postgres:14
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: merchant
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
     # - ./initdb:/docker-entrypoint-initdb.d/init.sql

  migrations:
    image: migrate/migrate
    command: -database postgres://root:secret@localhost:5431/merchant?sslmode=disable -verbose up
    volumes:
      - ./migration
    working_dir: /migration


